# Configuration file for scenario astlingen

# name of scearnio
env_name: astlingen
# time step (min)
control_interval: 5
# state definitions
states:
  - !!python/tuple
    - "RG1"
    - rainfall
  - !!python/tuple
    - "RG2"
    - rainfall
  - !!python/tuple
    - "RG3"
    - rainfall
  - !!python/tuple
    - "RG4"
    - rainfall
  - !!python/tuple
    - "T1"
    - depthN
  - !!python/tuple
    - "T2"
    - depthN
  - !!python/tuple
    - "T3"
    - depthN
  - !!python/tuple
    - "T4"
    - depthN
  - !!python/tuple
    - "T5"
    - depthN
  - !!python/tuple
    - "T6"
    - depthN
  - !!python/tuple
    - "V2"
    - setting
  - !!python/tuple
    - "V3"
    - setting
  - !!python/tuple
    - "V4"
    - setting
  - !!python/tuple
    - "V6"
    - setting

# Action space
action_space:
  V2:
    !!python/tuple
    - 0.1075
    - 0.2366
    - 1.0
  V3:
    !!python/tuple
    - 0.3159
    - 0.6508
    - 1.0
  V4:
    !!python/tuple
    - 0.1894
    - 0.3523
    - 1.0
  V6:
    !!python/tuple
    - 0.1687
    - 0.4303
    - 1.0

# Performance Targets
performance_targets:
  # CSOs to river
  - !!python/tuple
    - "T1"
    - cumflooding
    - 1
  - !!python/tuple
    - "T2"
    - cumflooding
    - 1
  - !!python/tuple
    - "T3"
    - cumflooding
    - 1
  - !!python/tuple
    - "T4"
    - cumflooding
    - 1
  - !!python/tuple
    - "T5"
    - cumflooding
    - 1
  - !!python/tuple
    - "CSO8"
    - cumflooding
    - 1
  - !!python/tuple
    - "CSO10"
    - cumflooding
    - 1
  # CSOs to creek
  - !!python/tuple
    - "T6"
    - cumflooding
    - 2
  - !!python/tuple
    - "CSO7"
    - cumflooding
    - 2
  - !!python/tuple
    - "CSO9"
    - cumflooding
    - 2
  # flow to WWTP
  - !!python/tuple # Conduit that connects upstream to "Out_to_WWTP" node
    - "Out_to_WWTP"
    - "totalinflow"
    - -0.1
  # control roughness
  - !!python/tuple # flow out of Tank1
    - "J19"
    - "totalinflow"
    - 0.01
  - !!python/tuple # flow out of Tank2
    - "J17"
    - "totalinflow"
    - 0.01
  - !!python/tuple # flow out of Tank3
    - "J14"
    - "totalinflow"
    - 0.01
  - !!python/tuple # flow out of Tank4
    - "J6"
    - "totalinflow"
    - 0.01
  - !!python/tuple # flow out of Tank5
    - "J2"
    - "totalinflow"
    - 0.01
  - !!python/tuple # flow out of Tank6
    - "J9"
    - "totalinflow"
    - 0.01

# distributed control sites
site:
  V2:
    states:
      - "RG3"
      - "T2"
      - "V2"
    action_space:
      - 0.1075
      - 0.2366
      - 1.0
  V3:
    states:
      - "RG1"
      - "RG2"
      - "T3"
      - "V3"
    action_space:
      - 0.3159
      - 0.6508
      - 1.0
  V4:
    states:
      - "RG3"
      - "T4"
      - "V4"
    action_space:
      - 0.1894
      - 0.3523
      - 1.0
  V6:
    states:
      - "RG2"
      - "T6"
      - "V6"
    action_space:
      - 0.1687
      - 0.4303
      - 1.0

# Rainfall scenario parameters
rainfall_timeseries: ast_rain # rainfall timeseries data
rainfall_events: ast_rain_events # rainfall timeseries data
MIET: 120 # minimum interevent time (min)
duration_range:  # rainfall duration sampling range (min)
  - 60
  - 100000
precipitation_range: # rainfall precipitation sampling range (mm)
  - 5
  - 15

# Model predictive control parameters
eval_horizon: 30 # Evaluation horizon (min)
hsf_dir: hsf # file path to save the hotstart file
eval_dir: eval # file path to save the evaluation file
suffix: mpc_eval_ # suffix of the evaluation file

