# Configuration file for scenario zeta

# name of scenario
env_name: chaohu
# control interval of scenario (min)
control_interval: 10
# designer rainfall parameters
rainfall_parameters: rainparas
# state definitions
states:
    - !!python/tuple
      - "-4"
      - cumprecip
    - !!python/tuple
      - "CC-storage"
      - depthN
    - !!python/tuple
      - "JK-storage"
      - depthN
    - !!python/tuple
      - "YS02001757"
      - depthN
    - !!python/tuple
      - "YS02001907"
      - depthN
    - !!python/tuple
      - "WS02006253"
      - depthN
    - !!python/tuple
      - "WS02006238"
      - depthN
    - !!python/tuple
      - "CC-1"
      - totalinflow        
    - !!python/tuple
      - "CC-2"
      - totalinflow        
    - !!python/tuple
      - "JK-1"
      - totalinflow 
    - !!python/tuple
      - "JK-2"
      - totalinflow


# Action space
# TODO: Use dict
action_space:
  CC-S1:
    !!python/tuple
    - 0
    - 1
  CC-S2:
    !!python/tuple
    - 0
    - 1
  CC-R1:
    !!python/tuple
    - 0
    - 1
  CC-R2:
    !!python/tuple
    - 0
    - 1
  JK-S:
    !!python/tuple
    - 0
    - 1
  JK-R1:
    !!python/tuple
    - 0
    - 1
  JK-R2:
    !!python/tuple
    - 0
    - 1

# Performance Targets
performance_targets:
  # flooding
  - !!python/tuple
    - "system"
    - cumflooding
    - 1
  # CSOs to river
  - !!python/tuple
    - "CC-1"
    - totalinflow      
    - 1  
  - !!python/tuple
    - "CC-2"
    - totalinflow      
    - 1  
  - !!python/tuple
    - "JK-1"
    - totalinflow 
    - 1
  - !!python/tuple
    - "JK-2"
    - totalinflow 
    - 1

# reward-related variables
reward:
  - !!python/tuple
    - "-5"
    - cumprecip
  - !!python/tuple
    - "CC-storage"
    - depthN
  - !!python/tuple
    - "JK-storage"
    - depthN
  - !!python/tuple
    - "system"
    - cumflooding
  - !!python/tuple
    - "CC-storage"
    - cumflooding
  - !!python/tuple
    - "JK-storage"
    - cumflooding
  - !!python/tuple
    - "CC-storage"
    - totalinflow
  - !!python/tuple
    - "JK-storage"
    - totalinflow
  - !!python/tuple
    - "CC-1"
    - totalinflow
  - !!python/tuple
    - "CC-2"
    - totalinflow
  - !!python/tuple
    - "JK-1"
    - totalinflow
  - !!python/tuple
    - "JK-2"
    - totalinflow
  - !!python/tuple
    - "CC-S1"
    - pumpenergy
  - !!python/tuple
    - "CC-S2"
    - pumpenergy
  - !!python/tuple
    - "CC-R1"
    - pumpenergy
  - !!python/tuple
    - "CC-R2"
    - pumpenergy
  - !!python/tuple
    - "JK-S"
    - pumpenergy
  - !!python/tuple
    - "JK-R1"
    - pumpenergy
  - !!python/tuple
    - "JK-R2"
    - pumpenergy

# distributed control sites
site:
  CC:
    states:
      - "-4"
      - "CC-storage"
      - "YS02001757"
      - "WS02006253"
      - "CC-1"
      - "CC-2"
    action_space:
      - !!python/tuple
        - "CC-S1"
        - "CC-S2"
      - !!python/tuple
        - "CC-R1"
        - "CC-R2"
  JK:
    states:
      - "-4"
      - "JK-storage"
      - "YS02001907"
      - "WS02006238"
      - "JK-1"
      - "JK-2"
    action_space:
      - !!python/tuple
        - "JK-S"
      - !!python/tuple
        - "JK-R1"
        - "JK-R2"


# Model predictive control parameters
# control horizon for predictive control (min)
control_horizon: 60
# Evaluation horizon (min)
eval_horizon: 60
# file path to save the hotstart file
hsf_dir: hsf
# file path to save the evaluation file
eval_dir: eval
# suffix of the evaluation file
suffix: mpc_eval_